name: goyobi
description: Grow Your Business.

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 
  cloud_firestore:
  intl: ">=0.14.0"
  flutter_circular_chart: 
  url_launcher:
  flutter_svg: ^0.5.5+1
  firebase_auth:
  sms: ^0.2.0
  datetime_picker_formfield:
  carousel_pro: ^0.0.13
  firebase_storage:



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/common/logo.png
    - assets/common/banner.jpg
    - assets/common/support.png
    - assets/common/sparkles.png
    - assets/tools/bmi/gender_arrow.svg
    - assets/tools/bmi/gender_female.svg
    - assets/tools/bmi/gender_male.svg
    - assets/tools/bmi/gender_other.svg
    - assets/tools/bmi/weight_arrow.svg
    - assets/tools/bmi/person.svg
    - assets/policy/fire.svg
    - assets/policy/dta.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
